name: "Apply PostgreSQL migrations"
description: "Automatically applies SQL migrations to your database"
author: Vladimir Levin
branding:
  icon: code
  color: purple
inputs:
  host:
    description: 'PostgreSQL host'
    required: true
  port:
    description: 'PostgreSQL port (default: 5432)'
    required: true
    default: '5432'
  username:
    description: 'PostgreSQL username'
    required: true
  password:
    description: 'PostgreSQL password'
    required: true
  ssl:
    description: "SSL enabled (default: 'true')"
    default: 'true'
  migrations:
    description: "Path to migrations folder"
    required: true
  db:
    required: true
    default: 'postgres'
    description: 'PostgreSQL database'
  to_file:
    required: false
    default: 'false'
    description: 'Save migration results to file'
outputs:
  migrations:
    description: Applied migrations list (or path to result if `to_file=true`)
runs:
  using: 'node20'
  main: 'action/index.js'
